### ISSUE TITLE
[Feature] Enhanced OBSERVATION Domain Model

### ISSUE THREAD

**Issue by apds-change-control** [parkingdata/spec#16]
## Background
In 2022, the **City of Antwerp** requested a series of incremental adjustments to the APDS OBSERVATION domain. They intended to use APDS in a tender specification for ANPR scan cars. AN analysis on their end revealed a number of fields they were lacking for the APDS model to be fit for purpose. 

The following diagram shows the definition at the time:
<img width="749" alt="Image" src="https://github.com/user-attachments/assets/41afaa3c-f5de-45f9-a3ac-f313a2490911" />

### GPS Precision
As you can see in the current APDS model, there are two components in the location information:
* the location of the observer (e.g. the scan car)
* the location of what is being observed (i.e. the parked vehicle)
According to the requestor, there should however be a possibility to provide an information about the GPS accuracy (PDOP – position dilution of precision).

### ANPR Recognition Result Confidence
The current APDS model allows to indicate that the observed vehicle has a credential of type licensePlate, and it also lets the data provider specify the method via which the credential id was obtained (in my example: anpr). They say they also need to be able to provide confidence factors indicating the accuracy likelihood of the automatically recognized license plate number. The request was made to be able to send both,
* an overall confidence factor as well as
* a matrix of confidence factors by character
This is something that I have come across with many ANPR camera providers, too.
Also, they’d like to be able to post information on the scan vehicle and its speed at the time of capturing data.
 
### Image Details
In the current version of the standard, APDS offers to attach one or more captured images to an observation element (either via a URL/link or as embedded image data). The only other attribute of an image is a unique id. The request has been made to offer the capability of storing additional details along with an image. Attributes that I saw in specification extracts were e.g.:
* camera id
* image type/content type, e.g. “overview” vs. “plate”
* (approximate) distance between camera and target

**Comment by apds-change-control** [comment]
## Approval
The APDS Change Control Group at the time (brepax@gmail.com, jon@harrodboot.com, bob.shepard@outlook.com, MLOCATELLI@interparking.com, markus.schneider@plexx-digital.com) worked with the City of Antwerp and approved the model changes documented by the City as follows:

```yaml
APDSObservation:
  description: 'This entity models a particular observation of a set of ANPR camera. The Observation might be done with several ANPR cameras, but is limited to the observation of ONE vehicle. It implements the APDS data model https://www.allianceforparkingdatastandards.org/'
  properties:
    address:
      description: The mailing address
      properties:
        addressCountry:
          description: 'The country. For example, Spain'
          type: string
          x-ngsi:
            model: https://schema.org/addressCountry
            type: Property
        addressLocality:
          description: 'The locality in which the street address is, and which is in the region'
          type: string
          x-ngsi:
            model: https://schema.org/addressLocality
            type: Property/
        addressRegion:
          description: 'The region in which the locality is, and which is in the country'
          type: string
          x-ngsi:
            model: https://schema.org/addressRegion
            type: Property
        district:
          description: 'A district is a type of administrative division that, in some countries, is managed by the local government'
          type: string
          x-ngsi:
            type: Property
        postOfficeBoxNumber:
          description: 'The post office box number for PO box addresses. For example, 03578'
          type: string
          x-ngsi:
            model: https://schema.org/postOfficeBoxNumber
            type: Property
        postalCode:
          description: 'The postal code. For example, 24004'
          type: string
          x-ngsi:
            model: https://schema.org/https://schema.org/postalCode
            type: Property
        streetAddress:
          description: The street address
          type: string
          x-ngsi:
            model: https://schema.org/streetAddress
            type: Property
        streetNr:
          description: Number identifying a specific property on a public street
          type: string
          x-ngsi:
            type: Property
      type: object
      x-ngsi:
        model: https://schema.org/address
        type: Property
    alternateName:
      description: An alternative name for this item
      type: string
      x-ngsi:
        type: Property
    areaServed:
      description: The geographic area where a service or offered item is provided
      type: string
      x-ngsi:
        model: https://schema.org/Text
        type: Property
    creator:
      description: Id of current driver.
      type: string
      x-ngsi:
        type: Property
    dataProvider:
      description: A sequence of characters identifying the provider of the harmonised data entity
      type: string
      x-ngsi:
        type: Property
    dateCreated:
      description: Entity creation timestamp. This will usually be allocated by the storage platform
      format: date-time
      type: string
      x-ngsi:
        type: Property
    dateModified:
      description: Timestamp of the last modification of the entity. This will usually be allocated by the storage platform
      format: date-time
      type: string
      x-ngsi:
        type: Property
    description:
      description: A description of this item
      type: string
      x-ngsi:
        type: Property
    id:
      anyOf:
        - description: Identifier format of any NGSI entity
          maxLength: 256
          minLength: 1
          pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
          type: string
          x-ngsi:
            type: Property
        - description: Identifier format of any NGSI entity
          format: uri
          type: string
          x-ngsi:
            type: Property
      description: Unique identifier of the entity
      x-ngsi:
        type: Property
    images:
      description: 'Array of links to images. The array element contain the URLs of the images and additional info. As an alternative to the images URL, the image itself can be included in the binaryContent attribute.'
      items:
        items:
          description: Every element in the array of images
          properties:
            URL:
              description: Uri of the image
              format: uri
              type: string
              x-ngsi:
                type: Property
            binaryContent:
              description: Binary format of the image content
              format: uuencoded
              type: string
              x-ngsi:
                type: Property
            camId:
              description: Identifier of the camera. It can be specified by the camera position (also used in the 'camera' attribute)
              type: string
              x-ngsi:
                type: Property
            distance:
              description: The distance in meters from the observer
              type: number
              x-ngsi:
                type: Property
                units: meters
            expiryDateTime:
              description: Timestamp until which the URL is valid
              format: date-time
              type: string
              x-ngsi:
                type: Property
            imageContent:
              description: It specifies the content of the image
              type: string
              x-ngsi:
                type: Property
          type: object
          x-ngsi:
            type: Property
        type: array
      type: array
      x-ngsi:
        type: Property
    location:
      description: 'Geojson reference to the item. It can be Point, LineString, Polygon, MultiPoint, MultiLineString or MultiPolygon'
      oneOf:
        - description: Geojson reference to the item. Point
          properties:
            bbox:
              items:
                type: number
              minItems: 4
              type: array
            coordinates:
              items:
                type: number
              minItems: 2
              type: array
            type:
              type: string
              enum:
                - Point
          required:
            - type
            - coordinates
          title: GeoJSON Point
          type: object
          x-ngsi:
            type: GeoProperty
        - description: Geojson reference to the item. LineString
          properties:
            bbox:
              items:
                type: number
              minItems: 4
              type: array
            coordinates:
              items:
                items:
                  type: number
                minItems: 2
                type: array
              minItems: 2
              type: array
            type:
              enum:
                - LineString
              type: string
          required:
            - type
            - coordinates
          title: GeoJSON LineString
          type: object
          x-ngsi:
            type: GeoProperty
        - description: Geojson reference to the item. Polygon
          properties:
            bbox:
              items:
                type: number
              minItems: 4
              type: array
            coordinates:
              items:
                items:
                  items:
                    type: number
                  minItems: 2
                  type: array
                minItems: 4
                type: array
              type: array
            type:
              enum:
                - Polygon
              type: string
          required:
            - type
            - coordinates
          title: GeoJSON Polygon
          type: object
          x-ngsi:
            type: GeoProperty
        - description: Geojson reference to the item. MultiPoint
          properties:
            bbox:
              items:
                type: number
              minItems: 4
              type: array
            coordinates:
              items:
                items:
                  type: number
                minItems: 2
                type: array
              type: array
            type:
              enum:
                - MultiPoint
              type: string
          required:
            - type
            - coordinates
          title: GeoJSON MultiPoint
          type: object
          x-ngsi:
            type: GeoProperty
        - description: Geojson reference to the item. MultiLineString
          properties:
            bbox:
              items:
                type: number
              minItems: 4
              type: array
            coordinates:
              items:
                items:
                  items:
                    type: number
                  minItems: 2
                  type: array
                minItems: 2
                type: array
              type: array
            type:
              enum:
                - MultiLineString
              type: string
          required:
            - type
            - coordinates
          title: GeoJSON MultiLineString
          type: object
          x-ngsi:
            type: GeoProperty
        - description: Geojson reference to the item. MultiLineString
          properties:
            bbox:
              items:
                type: number
              minItems: 4
              type: array
            coordinates:
              items:
                items:
                  items:
                    items:
                      type: number
                    minItems: 2
                    type: array
                  minItems: 4
                  type: array
                type: array
              type: array
            type:
              enum:
                - MultiPolygon
              type: string
          required:
            - type
            - coordinates
          title: GeoJSON MultiPolygon
          type: object
          x-ngsi:
            type: GeoProperty
      x-ngsi:
        type: GeoProperty
    name:
      description: The name of this item
      type: string
      x-ngsi:
        type: Property
    observationDateTime:
      description: The timestamp the Observation was made (UTC). Mandatory if observationStartDateTime and observationEndDateTime are not used.
      format: date-time
      type: string
      x-ngsi:
        type: Property
    observationEndDateTime:
      description: 'The date and time of the observation event ended(in UTC).(e.g.a car was observed to exit a delivery zone at 9: 33am). Mandatory if creationDateTime is not used.'
      format: date-time
      type: string
      x-ngsi:
        type: Property
    observationStartDateTime:
      description: 'The date and time of the observation(in UTC)event started.(e.g.a car was observed to enter a delivery zone at 8: 01am). Mandatory if creationDateTime is not used.'
      format: date-time
      type: string
      x-ngsi:
        type: Property
    observedCredentialCharacterConfidence:
      description: The confidence of individual character recognition. As with observedCredentialConfidence this is vendor specific. Use the metadata to indicate how the confidences can be interpreted.
      items:
        description: Every observation of the credential character confidence
        maximum: 1
        minimum: 0
        type: number
        x-ngsi:
          type: Property
      type: array
      x-ngsi:
        type: Property
    observedCredentialConfidence:
      description: 'The overall confidence of the measurement. This can be vendor specific, but should always be rescaled to value between 0 en 1. Use the metadata to indicate how this number should be interpreted. Arvoo: range[0.0, 1.0](higher is better).'
      maximum: 1
      minimum: 0
      type: number
      x-ngsi:
        type: Property
    observedCredentialCountry:
      description: 'Country Code following the 2 character ISO3166 standard (https://www.iban.com/country-codes). Note that the International vehicle registration code should not be used to avoid ambiguity (https://en.wikipedia.org/wiki/International_vehicle_registration_code). If the country-code could not be determined, set ''XX'' as for this attribute.'
      type: string
      x-ngsi:
        type: Property
    observedCredentialId:
      description: 'Specific identifier to the referenced observed credential. The credential is specified by observedCredentialType and may be an RFID tag, ticket number from a paystation, license plate number, etc. In case of a licensePlate only alpha numerical values (no spaces or hyphens) are allowed. Optionally an '':'' can be used to indicate the position of e.g. the German City Seal (https://www.europeanplates.com/information/german-city-codes.html).'
      type: string
      x-ngsi:
        type: Property
    observedCredentialType:
      description: 'Type of the credential referenced within  the observation. Allowed values are specified in the APDS CredentialType. Enum:''barcode, bluetooth, eticket, hangtag, licensePlate, permit, qrCode, rfid, ticket, other'''
      enum:
        - barcode
        - bluetooth
        - eticket
        - hangtag
        - licensePlate
        - permit
        - qrCode
        - rfid
        - ticket
        - other
      type: string
      x-ngsi:
        type: Property
    observedHeading:
      description: 'Denotes the direction of travel of the observer and is specified in decimal degrees, where 0 <= ''heading'' < 360, counting clockwise relative to the true north.If the vehicle is stationary(i.e. the value of the ''speed'' attribute is ''0''), then the value of the heading attribute must be equal to ''-1''. (UN code DD)'
      oneOf:
        - exclusiveMaximum: 360
          maximum: 360
          minimum: 0
          type: number
        - enum:
            - -1
          type: number
      x-ngsi:
        model: https://schema.org/Number
        type: Property
        units: Degrees
    observedLocation:
      description: GPS position of the middle position of the scanned vehicle.
      properties:
        address:
          description: The mailing address
          properties:
            addressCountry:
              description: 'The country. For example, Spain'
              type: string
              x-ngsi:
                model: https://schema.org/addressCountry
                type: Property
            addressLocality:
              description: 'The locality in which the street address is, and which is in the region'
              type: string
              x-ngsi:
                model: https://schema.org/addressLocality
                type: Property
            addressRegion:
              description: 'The region in which the locality is, and which is in the country'
              type: string
              x-ngsi:
                model: https://schema.org/addressRegion
                type: Property
            district:
              description: 'A district is a type of administrative division that, in some countries, is managed by the local government'
              type: string
              x-ngsi:
                type: Property
            postOfficeBoxNumber:
              description: 'The post office box number for PO box addresses. For example, 03578'
              type: string
              x-ngsi:
                model: https://schema.org/postOfficeBoxNumber
                type: Property
            postalCode:
              description: 'The postal code. For example, 24004'
              type: string
              x-ngsi:
                model: https://schema.org/https://schema.org/postalCode
                type: Property
            streetAddress:
              description: The street address
              type: string
              x-ngsi:
                model: https://schema.org/streetAddress
                type: Property
            streetNr:
              description: Number identifying a specific property on a public street
              type: string
              x-ngsi:
                type: Property
          type: object
          x-ngsi:
            model: https://schema.org/address
            type: Property
        areaServed:
          description: The geographic area where a service or offered item is provided
          type: string
          x-ngsi:
            model: https://schema.org/Text
            type: Property
        location:
          description: 'Geojson reference to the item. It can be Point, LineString, Polygon, MultiPoint, MultiLineString or MultiPolygon'
          oneOf:
            - bbox:
                items:
                  type: number
                minItems: 4
                type: array
              coordinates:
                items:
                  type: number
                minItems: 2
                type: array
              type:
                enum:
                  - Point
                type: string
            - bbox:
                items:
                  type: number
                minItems: 4
                type: array
              coordinates:
                items:
                  items:
                    type: number
                  minItems: 2
                  type: array
                minItems: 2
                type: array
              type:
                enum:
                  - LineString
                type: string
            - bbox:
                items:
                  type: number
                minItems: 4
                type: array
              coordinates:
                items:
                  items:
                    items:
                    minItems: 2
                    type: array
                  minItems: 4
                  type: array
                type: array
              type:
                enum:
                  - Polygon
                type: string
            - bbox:
                items:
                  type: number
                minItems: 4
                type: array
              coordinates:
                items:
                  items:
                    type: number
                  minItems: 2
                  type: array
                type: array
              type:
                enum:
                  - MultiPoint
                type: string
            - bbox:
                items:
                  type: number
                minItems: 4
                type: array
              coordinates:
                items:
                  items:
                    items:
                    minItems: 2
                    type: array
                  minItems: 2
                  type: array
                type: array
              type:
                enum:
                  - MultiLineString
                type: string
            - bbox:
                items:
                  type: number
                minItems: 4
                type: array
              coordinates:
                items:
                  items:
                    items:
                    minItems: 4
                    type: array
                  type: array
                type: array
              type:
                enum:
                  - MultiPolygon
                type: string
          x-ngsi:
            type: GeoProperty
      type: object
      x-ngsi:
        type: GeoProperty
    observedLocationPDOP:
      description: 'Accuracy of GPS position of the observed vehicle. This is expressed as ''Position Dilution Of Precision''(https: //en.wikipedia.org/wiki/Dilution_of_precision_(navigation)). (UN code ''MTR''). '
      type: number
      x-ngsi:
        type: Property
        units: meters
    observedMethod:
      description: 'The method of observation recorded for this observation element as defined by APDS (ObservationType). Enum:''anpr, chalk, visual, scanner, rfTranspoder, other'''
      enum:
        - anpr
        - chalk
        - other
        - rfTranspoder
        - scanner
        - visual
      type: string
      x-ngsi:
        type: Property
    observedSpeed:
      description: 'Denotes the magnitude of the horizontal component of the observed vehicles current velocity and is specified in kilometers per hour. If provided, the value of the speed attribute must be a non - negative real number.''-1'' MAY be used if speed is transiently unknown for some reason. (UN Code KMH).'
      oneOf:
        - minimum: 0
          type: number
        - maximum: -1
          minimum: -1
          type: number
      x-ngsi:
        model: https://schema.org/Number
        type: Property
        units: km/h
    observedVehicleColour:
      description: The colour of the observed vehicle
      type: string
      x-ngsi:
        type: Property
    observedVehicleMake:
      description: The make of the observed vehicle
      type: string
      x-ngsi:
        type: Property
    observedVehicleType:
      description: 'Type of vehicle from the point of view of its structural characteristics. This is different than the vehicle category . Enum:''agriculturalVehicle, anyVehicle, articulatedVehicle, bicycle, binTrolley, bus, car, caravan, carOrLightVehicle, carWithCaravan, carWithTrailer, cleaningTrolley, constructionOrMaintenanceVehicle, fourWheelDrive, highSidedVehicle, lorry, minibus, moped, motorcycle, motorcycleWithSideCar, motorscooter, sweepingMachine, tanker, threeWheeledVehicle, trailer, tram, twoWheeledVehicle, trolley, van, vehicleWithoutCatalyticConverter, vehicleWithCaravan, vehicleWithTrailer, withEvenNumberedRegistrationPlates, withOddNumberedRegistrationPlates, other''. The following values defined by _VehicleTypeEnum_ and _VehicleTypeEnum2_, [DATEX 2 version 2.3](http://d2docs.ndwcloud.nu/_static/umlmodel/v2.3/index.htm) and extended for other uses'
      enum:
        - agriculturalVehicle
        - ambulance
        - anyVehicle
        - articulatedVehicle
        - autorickshaw
        - bicycle
        - binTrolley
        - BRT mini busÂ·
        - BRT bus
        - bus
        - car
        - caravan
        - carOrLightVehicle
        - carWithCaravan
        - carWithTrailer
        - cleaningTrolley
        - compactor
        - constructionOrMaintenanceVehicle
        - dumper
        - e-moped
        - e-scooter
        - e-motorcycle
        - fireTender
        - fourWheelDrive
        - highSidedVehicle
        - hopper
        - lorry
        - minibus
        - moped
        - motorcycle
        - motorcycleWithSideCar
        - motorscooter
        - policeVan
        - publicMotor
        - sweepingMachine
        - tanker
        - tempo
        - threeWheeledVehicle
        - tipper
        - trailer
        - tram
        - trolley
        - twoWheeledVehicle
        - van
        - vehicleWithoutCatalyticConverter
        - vehicleWithCaravan
        - vehicleWithTrailer
        - withEvenNumberedRegistrationPlates
        - withOddNumberedRegistrationPlates
        - other
      type: string
      x-ngsi:
        model: https://schema.org/Text
        type: Property
    observer:
      description: The name or identification of the scanning system making the observation recorded in this observation element.
      type: string
      x-ngsi:
        type: Property
    observerCameras:
      description: 'Array of camera positions that detected the vehicle.The first camera in the list has the best recognition.Use the following abbreviations to indicate the camera positioning on a car: RF(Right Front), RM(Right Middle), RB(Right Back), LF(Left Front), LM(Left Middle), LB(Left Back).'
      items:
        description: Every camera position
        type: string
        x-ngsi:
          type: Property
      type: array
      x-ngsi:
        type: Property
    observerDescription:
      description: Free-text description for details of the observation or observer. Can e.g.be used as a friendly name of a specific ANPR scan car.
      type: string
      x-ngsi:
        type: Property
    observerHeading:
      description: 'Denotes the direction of travel of the observer and is specified in decimal degrees, where 0 <= ''heading'' < 360, counting clockwise relative to the true north. If the vehicle is stationary(i.e. the value of the ''speed'' attribute is ''0''), then the value of the heading attribute must be equal to ''-1'''
      oneOf:
        - exclusiveMaximum: 360
          maximum: 360
          minimum: 0
          type: number
        - enum:
            - -1
          type: number
      x-ngsi:
        model: https://schema.org/Number
        type: Property
        units: Degree.
    observerLocation:
      description: GPS position of the person or car equipped with the Camera/s that produce the observation.
      properties:
        address:
          description: The mailing address
          properties:
            addressCountry:
              description: 'The country. For example, Spain'
              type: string
              x-ngsi:
                model: https://schema.org/addressCountry
                type: Property
            addressLocality:
              description: 'The locality in which the street address is, and which is in the region'
              type: string
              x-ngsi:
                model: https://schema.org/addressLocality
                type: Property
            addressRegion:
              description: 'The region in which the locality is, and which is in the country'
              type: string
              x-ngsi:
                model: https://schema.org/addressRegion
                type: Property
            district:
              description: 'A district is a type of administrative division that, in some countries, is managed by the local government'
              type: string
              x-ngsi:
                type: Property
            postOfficeBoxNumber:
              description: 'The post office box number for PO box addresses. For example, 03578'
              type: string
              x-ngsi:
                model: https://schema.org/postOfficeBoxNumber
                type: Property
            postalCode:
              description: 'The postal code. For example, 24004'
              type: string
              x-ngsi:
                model: https://schema.org/https://schema.org/postalCode
                type: Property
            streetAddress:
              description: The street address
              type: string
              x-ngsi:
                model: https://schema.org/streetAddress
                type: Property
            streetNr:
              description: Number identifying a specific property on a public street
              type: string
              x-ngsi:
                type: Property
          type: object
          x-ngsi:
            model: https://schema.org/address
            type: Property
        areaServed:
          description: The geographic area where a service or offered item is provided
          type: string
          x-ngsi:
            model: https://schema.org/Text
            type: Property
        location:
          description: 'Geojson reference to the item. It can be Point, LineString, Polygon, MultiPoint, MultiLineString or MultiPolygon'
          oneOf:
            - bbox:
                items:
                  type: number
                minItems: 4
                type: array
              coordinates:
                items:
                  type: number
                minItems: 2
                type: array
              type:
                enum:
                  - Point
                type: string
            - bbox:
                items:
                  type: number
                minItems: 4
                type: array
              coordinates:
                items:
                  items:
                    type: number
                  minItems: 2
                  type: array
                minItems: 2
                type: array
              type:
                enum:
                  - LineString
                type: string
            - bbox:
                items:
                  type: number
                minItems: 4
                type: array
              coordinates:
                items:
                  items:
                    items:
                    minItems: 2
                    type: array
                  minItems: 4
                  type: array
                type: array
              type:
                enum:
                  - Polygon
                type: string
            - bbox:
                items:
                  type: number
                minItems: 4
                type: array
              coordinates:
                items:
                  items:
                    type: number
                  minItems: 2
                  type: array
                type: array
              type:
                enum:
                  - MultiPoint
                type: string
            - bbox:
                items:
                  type: number
                minItems: 4
                type: array
              coordinates:
                items:
                  items:
                    items:
                    minItems: 2
                    type: array
                  minItems: 2
                  type: array
                type: array
              type:
                enum:
                  - MultiLineString
                type: string
            - bbox:
                items:
                  type: number
                minItems: 4
                type: array
              coordinates:
                items:
                  items:
                    items:
                    minItems: 4
                    type: array
                  type: array
                type: array
              type:
                enum:
                  - MultiPolygon
                type: string
          x-ngsi:
            type: GeoProperty
      type: object
      x-ngsi:
        type: GeoProperty
    observerLocationPDOP:
      description: 'Accuracy of the GPS position of the observer, expressed as ''Position Dilution Of Precision''(https: //en.wikipedia.org/wiki/Dilution_of_precision_(navigation))'
      type: number
      x-ngsi:
        type: Property
        units: meters.
    observerSpeed:
      description: 'Denotes the magnitude of the horizontal component of the observer current velocity and is specified in kilometers per hour. If provided, the value of the speed attribute must be a non - negative real number. ''-1'' MAY be used if speed is transiently unknown for some reason'
      oneOf:
        - minimum: 0
          type: number
        - maximum: -1
          minimum: -1
          type: number
      x-ngsi:
        model: https://schema.org/Number
        type: Property
        units: 'KMH '
    owner:
      description: A List containing a JSON encoded sequence of characters referencing the unique Ids of the owner(s)
      items:
        anyOf:
          - description: Identifier format of any NGSI entity
            maxLength: 256
            minLength: 1
            pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
            type: string
            x-ngsi:
              type: Property
          - description: Identifier format of any NGSI entity
            format: uri
            type: string
            x-ngsi:
              type: Property
        description: Unique identifier of the entity
        x-ngsi:
          type: Property
      type: array
      x-ngsi:
        type: Property
    seeAlso:
      description: list of uri pointing to additional resources about the item
      oneOf:
        - items:
            format: uri
            type: string
          minItems: 1
          type: array
        - format: uri
          type: string
      x-ngsi:
        type: Property
    source:
      description: 'A sequence of characters giving the original source of the entity data as a URL. Recommended to be the fully qualified domain name of the source provider, or the URL to the source object'
      type: string
      x-ngsi:
        type: Property
    towardsObserver:
      description: '1: Observed vehicle moves in direction of camera, 0: Observed vehicle moves away direction of camera, -1: Observed vehicle direction not detected.'
      enum:
        - -1
        - 0
        - 1
      type: number
      x-ngsi:
        type: Property
    type:
      description: NGSI Entity type. It has to be APDSObservation
      enum:
        - APDSObservation
      type: string
      x-ngsi:
        type: Property
  required:
    - id
    - type
  type: object
  x-derived-from: https://www.allianceforparkingdatastandards.org/
  x-disclaimer: 'Redistribution and use in source and binary forms, with or without modification, are permitted  provided that the license conditions are met. Copyleft (c) 2022 Contributors to Smart Data Models Program'
  x-license-url: https://github.com/smart-data-models/dataModel.Transportation/blob/master/APDSObservation/LICENSE.md
  x-model-schema: https://smart-data-models.github.io/dataModel.Transportation/APDSObservation/schema.json
  x-model-tags: ""
  x-version: 0.0.1
```
