### ISSUE TITLE
[Feature] Generic Extension Mechanism

### ISSUE THREAD

**Issue by apds-change-control** [parkingdata/spec#22]
Other standards (like e.g. Datex II) offer mechanisms for implementors to specify enhancements to the model classes in a defined manner. APDS does not define how to handle enhancements.

A generic mechanism for extensions shall be specified and added to the standard.

**Comment by Zezake** [comment]
After reviewing how DATEX II or other systems handle extensions i propose the following:

- Have a dedicated package called Extensions to manage all modifications while they don't become "oficial".
- Usage of _D2BLevelExtension_ relationship to identify extensions.
- Usage of _[Parameter]EnumExtension_ to extend enum lists.

### Core Principles of DATEX II Extensibility

The fundamental goal is to allow implementers to add specific information to the data model while maintaining interoperability with standard systems. The key principles are:

- **Model-Based Extensions**: Extensions are preferably created in the UML model, not by manually editing the generated XML schemas.
- **Backward Compatibility**: The primary extension mechanism (Level B) ensures that standard-compliant systems can process messages with extensions, even if they don't understand the extended content, by simply ignoring it.
- **Namespace Segregation**: Extensions must be defined in a separate namespace to prevent conflicts with the core DATEX II model or other extensions. This provides modularity.

### How Compatible Extensions are Implemented

To ensure compatibility, Level B extensions follow specific rules within the UML model:

1. **Use of Extension Packages**: All extensions should be placed in a dedicated "Extension" package within the UML model, with each specific extension residing in its own sub-package. They should be part of a namespace called `Extension`.
    1. Is not an extension it self, is a container for the extensions.
    2. This has **no functional impact** on the core model. It is a modeling best practice that organizes extensions.
    3. Datex II example: [https://datex-ii-eu.github.io/datexiimodel/EARoot/EA1.htm](url)
    
2. **Extending Classes**: to add new attributes or data fields to an existing data structure in the standard. This is used when you need to capture supplementary information that is not part of the core model. This new class is then linked to the original class using a `D2BLevelExtension` UML relationship, indicating it is an extension. You cannot extend an existing extension class.
    1. This is **fully backward-compatible**. A standard system receiving data with this extension will correctly read and process all the information from the original data  class. When it encounters the extended data, it will recognize it as a Level B extension and simply ignore it without causing an error. The core data remains 100% usable.
    2. Example: City Parking authority is using the APDS and wants to link the Rights to the government Policy that controls the Right and Rates Logic. A new class called `governmentPolicy` will be linked to the `RightSpecification` object via a `D2BLevelExtension`
3. **Extending Enumerations**: Similarly, to add new values to an existing list (an enumeration), a new enumeration is created in the extension package and linked to the original with the `D2BLevelExtension` relationship. This allows for the addition of new literals.
    1. This is **almost backward-compatible**. A standard system receiving a message containing an extended value (like `e-scooter`) will check it against its list of known vehicle types. Since `e-scooter` is not on its list, the system will not recognize the value. The system will only failg if the parameter is mandatory, if not it should ingore the specific attribute.
    2. Example: if adding new vehicle type, the enum list **VehicleTypesEnum** will be related to its extension **VehicleTypesEnumExtended.**

**Comment by plexxdigital** [comment]
[Draft Version Aleix Martinez]

# Generic Extension Mechanism

## Goal
Enable safe, discoverable extensions to APDS so implementers can add data without breaking
receivers.

**Brief Explanation:** This proposal introduces a unified method for attaching custom information
to APDS entities using a standard extensions container, versioned namespaces, and clear
enum extension patterns. This ensures new data can be added without disrupting existing
systems, while remaining easy to detect, validate, and safely ignore if unsupported.

---

## 1) Core Rules
* **Compatibility**: Receivers **MUST** process the core and safely ignore unknown extensions.
* **JSON/OpenAPI Container**: Every APDS class **MUST** include an optional extensions
map { namespace → object }.
* **Open Enums**: Keep the core enum; additional literals go in a companion field with
**coreMapping** if required.

## 2) How to Extend (Example: RateTable)
### 2.0 Extension Container
> Define a reusable `ExtensionContainer` to be included in any APDS entity providing a
consistent and predictable way to attach extensions.

```yaml

# file: ../common/ExtensionsContainer.yaml
title: ExtensionsContainer
description: Standard container for APDS extensions (namespace → payload)
type: object
properties:
    extensions:
        type: object
        description: Map of extension namespace → payload (e.g., apds-ext:{org}:{extensionName}@{semver})
    propertyNames:
        pattern: "^[a-z0-9\\-.:@]+$"
    additionalProperties:
        type: object

```

### 2.1 Universal extensions
> A standard `extensions` section is added to every APDS entity.
The entity name within this section is defined by its namespace pattern `apds-ext:{organization}{extensionName}@{version}` , which clearly identifies who created the extension, its purpose, and its version.
> This predictable structure keeps all custom data organized, ensures consistency, makes detection and validation straightforward, and follows unsupported extensions to be safely ignored.

```yaml

# file: ./rate/extensions/GovernmentPolicy.yaml
title: GovernmentPolicy
description: Government policy defining the legal and regulatory framework
for parking rate Table.
x-tag:
  - rate
  - extension
allOf:
  - $ref: ../common/VersionedIdentity.yaml
  - type: object
    properties:
    governmentPolicyName:
        $ref: ../common/MultilingualString.yaml
    description:
        type: string
        description: Government policy applied with this Right.
    policySupersedeId:
        $ref: ../right/GovernmentPolicy.yaml
   validityStart:
        type: string
        format: date-time
        description: When the policy starts applying.
    validityEnd:
        type: string
        format: date-time
        description: Until when the policy applies.
    required: [governmentPolicyName, vailidityStart]

```

### 2.2 Open Enum Pattern on rateType
> Keeps the main `RateTypeEnum` fixed for consistency while allowing new values in a
separate extension field. This enables the addition of new types without breaking systems
that only recognize the original list, while mapping them back to a core value when needed.
This ensures forward flexibility and backward compatibility.

```yaml

# file: ./enums/extensions/RateTypeExtension.yaml
title: RateTypeExtension
type: object
x-tags:
    - enumeration
    - extension
properties:
    namespace:
        type: string
        value: apds-ext:mitte-parking:rate-types@1.0.0
    code:
        type: string
        enums:
            - dynamic
            - monthly
    coreMapping:
        $ref: ../enums/RateTypeEnum.yaml
        description: Required when 'rateType' is mandatory and an external literal is used.
    label:
        type: string
required:
    - namespace
    - code

```

### 2.3 Extend entity properties (RateTable)
> Extend an entity with new fields beyond enums. For example, adding business rules or
metadata. We can create an extension schema

```yaml

# file: ../rate/extensions/RateTableExtra.yaml
title: RateTableExtra
type: object
properties:
    namespace:
        type: string
    roundingRule:
        type: string
        description: "Rounding of the rate value"
        enums: [UP, DOWN, NEAR]
    required:
        - roundingRule

```

### 2.4 Specialize known namespaces in rateTable
> While the `extensions` container is open, known namespaces can be specialized for
validation. This ensures stricter control for well-known extensions while still supporting
arbitrary ones.

```yaml

# add under the same 'type: object' where properties are defined (above)
    properties:
      # ... (core fields)
    extensions:
        type: object
        $ref: ../common/ExtensionsContainer.yaml
        properties:
            "apds-ext:mitte-parking:rate-types@1.0.0":
                $ref: ../extensions/enums/RateTypeExtension.yaml
            "apds-ext:mitte-parking:gov-policy@1.2.0":
                $ref: ../extensions/GovernmentPolicy.yaml
            "apds-ext:mitte-parking:rate-types@1.0.0":
                $ref: ../extensions/RateTableExtra.yaml

```

## 3. Serialization Example:

```json

{
  "rateTableName": {
    "en": "Downtown Day Pass"
  },
  "validityStart": "2025-07-01T00:00:00Z",
  "availability": "PUBLIC",
  "rateType": "hourly", // Because the rateType is mandatory,
  //..... other required fields for rateTable
  "rateTypeExtension": {
    "namespace": "apds-ext:mitte-parking:rate-types@1.0.0",
    "code": "dynamic",
    "coreMapping": "hourly"
  },
  "extensions": {
    "apds-ext:mitte-parking:gov-policy@1.2.0": {
      "governmentPolicyName": "GREEN Zone Rates 2025",
      "validityStart": "2025-01-01T05:00:00Z"
    },
    "apds-ext:mitte-parking:rate-table-extra@1.0.0": {
      "roundingType": "UP"
    }
  }
}
```
