### ISSUE TITLE
[Feature] Additional Tariff Properties

### ISSUE THREAD

**Issue by apds-change-control** [parkingdata/spec#25]
The team has come across tariff scenarios
requiring additional properties
to be adequately represented
in the APDS model
(e.g. required for the UK National Parking Platform)

**Comment by apds-change-control** [comment]
## Draft
A draft change was discussed last year but not finally assessed and decided. Here are the details from that discussion:

I have identified some settings actively used in the UK National Parking Platform location
template that do not have an APDS equivalent. Currently, I see four such settings:

* Overpayment policy (TariffEndCutOff / FullTimePurchased / CreditCarryOver)
* Follow-through policy (allowed / not allowed)
* Prepayment of a yet-to-come charging period
* Availability of prebooking

I see at least two different approaches to modeling this in APDS.

### Variant 1: specific
This approach defines the four settings above and their possible values. Nothing less, but also
nothing more than this.
The Open API specification would be something like this:

```yaml
RateSettings:
  type: object
  properties:
    overPaymentPolicy:
      type: string
      enum:
        - tariffEndCutOff
        - fullTimePurchased
        - creditCarryOver
        - other
    tariffFollowThroughAllowed:
      type: boolean
    prepayNextChargingPeriodAllowed:
      type: boolean
    preBookingAvailable:
      type: boolean
```

…and an example payload would look like this:

```json
{
    "rateSettings": {
        "overPaymentPolicy": "creditCarryOver",
        "tariffFollowThroughAllowed": true,
        "prePayNextChargingPeriodAllowed": true,
        "preBookingAvailable": false
    }
}
```

This would cover our current needs, but not offer any provision for potential additions.

### Variant 2: flexible
This second approach would be more flexible (extensible) but would require the platform
members to agree on some conventions. It essentially is just a list of key/value pairs
with arbitrary names and values.

Open API specification:

```yaml
RateSettings:
  type: array
  items:
    type: object
    properties:
      name:
        type: string
      value:
        oneOf:
           - type: string
           - type: boolean
           - type: number
           - type: integer
           - type: array
           - type: object
```

…example payload:

```json
{
    "rateSettings": [
        { "name": "overPaymentPolicy", "value": "creditCarryOver"},
        { "name": "tariffFollowThroughAllowed", "value": true},
        { "name": "prePayNextChargingPeriodAllowed", "value": true},
        { "name": "preBookingAvailable", "value": false}
    ]
}
```

I know that both approaches have pros and cons. Any preference?
Also, the question is which class should be the anchor for this settings container. I think it
cannot be the RateTable class itself as some settings are cross-tariff settings, so I am leaning
towards RightSpecification or RateEligibility.
